
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkjzjsohcklwwgmiroth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impranpqc29oY2tsd3dnbWlyb3RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MTg0ODMsImV4cCI6MjA1ODM5NDQ4M30.NUFRjP_syCcuHTfpbf9p9-c14kAEnG6NIv0Hk09JPUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'streamify-auth',
    detectSessionInUrl: false, // Set to false to prevent automatic redirects after email confirmations
    flowType: 'pkce',
  }
});
